project_id = "hmwnkhgsocdevehebjpq"

[functions.youtube-stats]
verify_jwt = false

[functions.instagram-stats]
verify_jwt = false

[functions.tiktok-auth]
verify_jwt = false

[functions.tiktok-stats]
verify_jwt = false
